//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Common;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Core.EntityClient;

    public partial class ContactManagerDBEntities : DbContext
    {
        public ContactManagerDBEntities()
            : base("name=ContactManagerDBEntities")
        {

        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {

            throw new UnintentionalCodeFirstException();
        }
        public virtual DbSet<Contact> Contacts { get; set; }
    }
}
