//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Common;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Core.EntityClient;

    public partial class ContactManagerDBEntities : ObjectContext
    {
        public ContactManagerDBEntities()
            : base("name=ContactManagerDBEntities", "ContactManagerDBEntities")
        {
            this.OnContextCreated();
        }
        public ContactManagerDBEntities(string connectionString) :
                base(connectionString, "ContactManagerDBEntities")
        {
            this.OnContextCreated();
        }

        public ContactManagerDBEntities(EntityConnection connection) :
                base(connection, "ContactManagerDBEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();

        public ObjectQuery< Contact> ContactSet
        {
            get
            {
                if ((this._ContactSet == null))
                {
                    this._ContactSet = base.CreateQuery<Contact>("[ContactSet]");
                }
                return this._ContactSet;
            }
        }

        private ObjectQuery<Contact> _ContactSet;
        //public virtual DbSet<Contact> Contacts { get; set; }

        public void AddToContactSet(Contact contact)
        {
            base.AddObject("ContactSet", contact);
        }


        [System.Data.Entity.Core.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName = "Models", Name = "Contact")]
        [System.Runtime.Serialization.DataContractAttribute(IsReference = true)]
        [System.Serializable()]
        public partial class Contact : System.Data.Entity.Core.Objects.DataClasses.EntityObject
        {
            /// <summary>
            /// Create a new Contact object.
            /// </summary>
            /// <param name="id">Initial value of Id.</param>
            /// <param name="firstName">Initial value of FirstName.</param>
            /// <param name="lastName">Initial value of LastName.</param>
            /// <param name="phone">Initial value of Phone.</param>
            /// <param name="email">Initial value of Email.</param>
            public static Contact CreateContact(int id, string firstName, string lastName, string phone, string email)
            {
                Contact contact = new Contact();
                contact.Id = id;
                contact.FirstName = firstName;
                contact.LastName = lastName;
                contact.Phone = phone;
                contact.Email = email;
                return contact;
            }
            /// <summary>
            /// There are no comments for Property Id in the schema.
            /// </summary>
            [System.Runtime.Serialization.DataMemberAttribute()]
            [System.Data.Entity.Core.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable = false)]
            public int Id
            {
                get
                {
                    return this._Id;
                }
                set
                {
                    this.OnIdChanging(value);
                    this.ReportPropertyChanging("Id");
                    this._Id = System.Data.Entity.Core.Objects.DataClasses.StructuralObject.SetValidValue(value);
                    this.ReportPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
            private int _Id;
            partial void OnIdChanging(int value);
            partial void OnIdChanged();
            /// <summary>
            /// There are no comments for Property FirstName in the schema.
            /// </summary>
            [System.Data.Entity.Core.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable = false)]
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string FirstName
            {
                get
                {
                    return this._FirstName;
                }
                set
                {
                    this.OnFirstNameChanging(value);
                    this.ReportPropertyChanging("FirstName");
                    this._FirstName = System.Data.Entity.Core.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                    this.ReportPropertyChanged("FirstName");
                    this.OnFirstNameChanged();
                }
            }
            private string _FirstName;
            partial void OnFirstNameChanging(string value);
            partial void OnFirstNameChanged();
            /// <summary>
            /// There are no comments for Property LastName in the schema.
            /// </summary>
            [System.Data.Entity.Core.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable = false)]
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string LastName
            {
                get
                {
                    return this._LastName;
                }
                set
                {
                    this.OnLastNameChanging(value);
                    this.ReportPropertyChanging("LastName");
                    this._LastName = System.Data.Entity.Core.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                    this.ReportPropertyChanged("LastName");
                    this.OnLastNameChanged();
                }
            }
            private string _LastName;
            partial void OnLastNameChanging(string value);
            partial void OnLastNameChanged();
            /// <summary>
            /// There are no comments for Property Phone in the schema.
            /// </summary>
            [System.Data.Entity.Core.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable = false)]
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Phone
            {
                get
                {
                    return this._Phone;
                }
                set
                {
                    this.OnPhoneChanging(value);
                    this.ReportPropertyChanging("Phone");
                    this._Phone = System.Data.Entity.Core.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                    this.ReportPropertyChanged("Phone");
                    this.OnPhoneChanged();
                }
            }
            private string _Phone;
            partial void OnPhoneChanging(string value);
            partial void OnPhoneChanged();
            /// <summary>
            /// There are no comments for Property Email in the schema.
            /// </summary>
            [System.Data.Entity.Core.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable = false)]
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Email
            {
                get
                {
                    return this._Email;
                }
                set
                {
                    this.OnEmailChanging(value);
                    this.ReportPropertyChanging("Email");
                    this._Email = System.Data.Entity.Core.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                    this.ReportPropertyChanged("Email");
                    this.OnEmailChanged();
                }
            }
            private string _Email;
            partial void OnEmailChanging(string value);
            partial void OnEmailChanged();

            [System.Data.Entity.Core.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable = false)]
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Status
            {
                get
                {
                    return this._Status;
                }
                set
                {
                    this.OnStatusChanging(value);
                    this.ReportPropertyChanging("Status");
                    this._Status = System.Data.Entity.Core.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                    this.ReportPropertyChanged("Status");
                    this.OnStatusChanged();
                }
            }
            private string _Status;
            partial void OnStatusChanging(string value);
            partial void OnStatusChanged();
        }

        internal void AddToContactSet(Models.Contact contactToCreate)
        {
            throw new NotImplementedException();
        }
    }
}
